#!/usr/bin/env python3

import sys
from stepmania_map import StepmaniaMap

TEMPLATE_PATH="./assets/stepmania/template.sm"

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage: from_osu <beatmap_file> <output_file>")
        sys.exit(1)

    smap = StepmaniaMap(TEMPLATE_PATH)
    
    source_file = sys.argv[1]
    output_file = sys.argv[2]

    smap.load_from_file(source_file)
    smap.write_sm_beatmap(output_file)

## Steps:
# Write 'Offset' From TimingSections[0]
# Write BPMs from TimingSections
# Use 'Fractions' to map beats to measures, preference for smallest fractions
